<?php

use Illuminate\Database\Seeder;

class DependenciasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //dependencias
        DB::table('dependencias')->insert([

                //Facultades
            ['dependencia' => 'Vicerrectorado Academico', 'organiza_diplomado'=>null, 'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null,  'dependencia_id'=> null, 'es_dep_ac'=>null, 'es_centro_generador'=>null, 'departamento_dependencia_id'=>null,],
//Facultades
            ['dependencia' => 'Facultad de Ciencias Agrarias', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null, 'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Medicina', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Psicología', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Enfermería', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Obstetricia', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Ciencias Administrativas y Turismo', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Ciencias Contables y Financieras', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Economía', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Ciencias Sociales', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Ciencias de la Educación', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Derecho y Ciencias Políticas', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Ingeniería Civil y Arquitectura', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Ingeniería Industrial y de Sistemas', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Facultad de Medicina Veterinaria y Zootecnia', 'organiza_diplomado'=>null,'es_facultad'=>'1', 'es_escuela'=>null, 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '1', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
//Escuelas
            ['dependencia' => 'Escuela Profesional INGENIERIA AGRONOMICA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 2, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>44,],
            ['dependencia' => 'Escuela Profesional INGENIERIA AGROINDUSTRIAL', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 2, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>45,],
            ['dependencia' => 'Escuela Profesional INGENIERIA AGROPECUARIA FORESTAL', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 2, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Escuela Profesional MEDICINA HUMANA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 3, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>46,],
            ['dependencia' => 'Escuela Profesional ODONTOLOGIA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 3, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>46,],
            ['dependencia' => 'Escuela Profesional PSICOLOGIA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 4, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>47,],
            ['dependencia' => 'Escuela Profesional ENFERMERIA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 5, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>48,],
            ['dependencia' => 'Escuela Profesional OBSTETRICIA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1','es_posgrado'=>null,'es_direccion'=>null,'es_oficina'=>null,'dependencia_id'=> 6,'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>49,],
            ['dependencia' => 'Escuela Profesional CIENCIAS ADMINISTRATIVAS', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 7, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>50,],
            ['dependencia' => 'Escuela Profesional TURISMO Y HOTELERIA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 7, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>50,],
            ['dependencia' => 'Escuela Profesional CIENCIAS CONTABLES Y FINANCIERAS', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 8, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>51,],
            ['dependencia' => 'Escuela Profesional ECONOMIA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 9, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>52,],
            ['dependencia' => 'Escuela Profesional SOCIOLOGIA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 10, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>53,],
            ['dependencia' => 'Escuela Profesional CIENCIAS DE LA COMUNICACION SOCIAL', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 10, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>53,],
            ['dependencia' => 'Escuela Profesional EDUCACION INICIAL', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 11, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>55,],
            ['dependencia' => 'Escuela Profesional EDUCACION PRIMARIA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 11, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>55,],
            ['dependencia' => 'Escuela Profesional EDUCACION FISICA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 11, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>54,],
            ['dependencia' => 'Escuela Profesional FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 11, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>55,],
            ['dependencia' => 'Escuela Profesional LENGUA Y LITERATURA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 11, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>55,],
            ['dependencia' => 'Escuela Profesional CIENCIAS HISTORICO SOCIALES Y GEOGRAFICAS', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 11, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>55,],
            ['dependencia' => 'Escuela Profesional MATEMATICA Y FISICA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 11, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>54,],
            ['dependencia' => 'Escuela Profesional BIOLOGIA, QUIMICA Y CIENCIA DEL AMBIENTE', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 11, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>54,],
            ['dependencia' => 'Escuela Profesional DERECHO Y CIENCIAS POLITICAS', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 12, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>56,],
            ['dependencia' => 'Escuela Profesional INGENIERIA CIVIL', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 13, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>57,],
            ['dependencia' => 'Escuela Profesional ARQUITECTURA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> '13', 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>57,],
            ['dependencia' => 'Escuela Profesional INGENIERIA INDUSTRIAL', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 14, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>58,],
            ['dependencia' => 'Escuela Profesional INGENIERIA DE SISTEMAS', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 14, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>58,],
            ['dependencia' => 'Escuela Profesional MEDICINA VETERINARIA', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>'1', 'es_posgrado'=>null,'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 15, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>59,],
//departamentos academicos
            ['dependencia' => 'Departamento Académico de Ingeniería Agronómica', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 2, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Ingeniería Agroindustrial', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=>2, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Medicina y Odontología', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=>3, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Psicología', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 4, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Enfermería', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 5, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Obstetricia', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 6, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Ciencias Admisnistrativas y Turismo y Hotelería', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 7, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Ciencas Contables y Financieras', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 8, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Economía', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 9, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Sociología y Ciencias de la Comunicación', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 10, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico Pedagógico de Ciencias Formales y Naturales', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 11, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico Pedagógico de Ciencias Sociales y Humanidades', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 11, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Derecho y Ciencias Políticas', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 12, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Ingeniería Civil y Arquitectura', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 13, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Ingeniería Industrial y de Sistemas', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 14, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'Departamento Académico de Medicina Veterinaría', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 15, 'es_dep_ac'=>1,'es_centro_generador'=>null,'departamento_dependencia_id'=>null,],
//otros
            ['dependencia' => 'Dirección de Admisión', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>1, 'es_oficina'=>null, 'dependencia_id'=> 1, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],//60
            ['dependencia' => 'CEPREVAL', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> 1, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],//61
            ['dependencia' => 'Escuela de Posgrado', 'organiza_diplomado'=>1,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>1, 'es_direccion'=>null, 'es_oficina'=>null, 'dependencia_id'=> null, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'PROCAPT', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null,'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>1, 'dependencia_id'=> 1, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,],
            ['dependencia' => 'PROMASTER', 'organiza_diplomado'=>null,'es_facultad'=>null, 'es_escuela'=>null, 'es_posgrado'=>null, 'es_direccion'=>null, 'es_oficina'=>1, 'dependencia_id'=> 44, 'es_dep_ac'=>null,'es_centro_generador'=>1,'departamento_dependencia_id'=>null,]
            ]);
    }
}
